# Generated by Django 3.2.8 on 2021-10-15 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_number', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='Test Location', max_length=100)),
                ('status', models.CharField(default='Available', max_length=100)),
                ('last_refill', models.DateField(null=True)),
                ('next_refill', models.DateField(null=True)),
                ('min_balance', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='Test', max_length=100)),
                ('date_issued', models.DateField(null=True)),
                ('date_expires', models.DateField(null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(default='Test', max_length=100)),
                ('account_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pin', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('balance', models.IntegerField(default=0)),
                ('bank_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
