# Generated by Django 3.2.8 on 2021-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211014_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='Test123!', max_length=100),
        ),
    ]
